### PR TITLE
Add more dependencies

### PR DESCRIPTION
**Pull request by gratuxri**

### CODE REVIEW

**Comment by WolfgangFahl** [comment]
Could you please explain your needs in https://gitter.im/play-chess-with-a-webcam/community and or here?

**Comment by WolfgangFahl** [comment]
This pull request makes travis choke ...

**Comment by WolfgangFahl** [comment]
This still of installation breaks the travis scripts. What would be the alternative?

**Comment by gratuxri** [comment]
Which one? please give me more feadback. This branch  successfull builds with travis:  https://travis-ci.org/WolfgangFahl/play-chess-with-a-webcam/jobs/636005930 Which line do you mean?

**Pull request merged**
